#include "tr_local.h"
#include "vk.h"

#define CASE_STR(x) \
	case (x):       \
		return #x

const char *vk_format_string(VkFormat format)
{
	static char buf[16];

	switch (format)
	{
		// color formats
		CASE_STR(VK_FORMAT_R5G5B5A1_UNORM_PACK16);
		CASE_STR(VK_FORMAT_B5G5R5A1_UNORM_PACK16);
		CASE_STR(VK_FORMAT_R5G6B5_UNORM_PACK16);
		CASE_STR(VK_FORMAT_B5G6R5_UNORM_PACK16);
		CASE_STR(VK_FORMAT_B8G8R8A8_SRGB);
		CASE_STR(VK_FORMAT_R8G8B8A8_SRGB);
		CASE_STR(VK_FORMAT_B8G8R8A8_SNORM);
		CASE_STR(VK_FORMAT_R8G8B8A8_SNORM);
		CASE_STR(VK_FORMAT_B8G8R8A8_UNORM);
		CASE_STR(VK_FORMAT_R8G8B8A8_UNORM);
		CASE_STR(VK_FORMAT_B4G4R4A4_UNORM_PACK16);
		CASE_STR(VK_FORMAT_R4G4B4A4_UNORM_PACK16);
		CASE_STR(VK_FORMAT_R16G16B16A16_UNORM);
		CASE_STR(VK_FORMAT_A2B10G10R10_UNORM_PACK32);
		CASE_STR(VK_FORMAT_A2R10G10B10_UNORM_PACK32);
		CASE_STR(VK_FORMAT_B10G11R11_UFLOAT_PACK32);
		// depth formats
		CASE_STR(VK_FORMAT_D16_UNORM);
		CASE_STR(VK_FORMAT_D16_UNORM_S8_UINT);
		CASE_STR(VK_FORMAT_X8_D24_UNORM_PACK32);
		CASE_STR(VK_FORMAT_D24_UNORM_S8_UINT);
		CASE_STR(VK_FORMAT_D32_SFLOAT);
		CASE_STR(VK_FORMAT_D32_SFLOAT_S8_UINT);
	default:
		Com_sprintf(buf, sizeof(buf), "#%i", format);
		return buf;
	}
}

#undef CASE_STR

